apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kube-proxy-rs-tls-cert
  namespace: kube-pattern
spec:
  secretName: kube-proxy-rs-tls-cert
  secretTemplate:
    annotations:
      kubed.appscode.com/sync: "amdp.io/tls=enabled"
      update: d156c439bdaa8494fad7d77733fce8f2
  renewBefore: 240h
  dnsNames:
  - 'kube-proxy-rs.amdp-dev.skamdp.org'
  issuerRef:
    group: cert-manager.io
    name: letsencrypt-prod
    kind: ClusterIssuer

