apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kube-proxy-rs-tls-cert
  namespace: part-rde
spec:
  secretName: kube-proxy-rs-tls-cert
  secretTemplate:
    annotations:
      kubed.appscode.com/sync: "amdp.io/tls=enabled"
      update: 60fdf1d2989a7f29f14f553edc92a4c3
  renewBefore: 240h
  dnsNames:
  - 'kube-proxy-rs.amdp-dev.skamdp.org'
  issuerRef:
    group: cert-manager.io
    name: letsencrypt-prod
    kind: ClusterIssuer

