apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-proxy-deployment
  namespace: part-rde
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kube-proxy
  template:
    metadata:
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '8081'
        prometheus.io/path: '/actuator/prometheus'
        update: f60275ea0b3431b0864e73561db8556e
      labels:
        app: kube-proxy
    spec:
      imagePullSecrets:
      - name: harbor-registry-secret
      containers:
      - name: kube-proxy
        image: amdp-registry.skamdp.org/mydev-ywyi/kube-proxy:IDE.1.0.6.INT
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: LOGGING_LEVEL
          value: INFO
        - name: DATASOURCE_URL
          valueFrom:
            secretKeyRef:
              name: datasource-secrets
              key: database-url
        - name: DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: datasource-secrets
              key: database-username
        - name: DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: datasource-secrets
              key: database-password
        - name: IDE_PROXY_DOMAIN
          value: kube-proxy.amdp-dev.skamdp.org
        - name: KEYCLOAK_CLIENT_ID
          value: kube-proxy-renew
        - name: KEYCLOAK_CLIENT_SECRET
          value: B3x4C4DARIYPVemmXghmxZZdFGhfofWN
