apiVersion: v1
kind: Service
metadata:
  name: kube-proxy-service
  namespace: part-rde
spec:
  selector:
    app: kube-proxy
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP


